# Generated by Django 4.2.6 on 2023-10-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evoapp", "0002_user_last_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
    ]
